# Generated by Django 5.0 on 2025-11-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
